### ISSUE TITLE
FORMAT_BDOC is not supported?

### ISSUE THREAD

**Issue by hsynff** [open-eid/digidoc4j#101]
In the legacy version of digidoc4j (jdigidoc) there was a field for bdoc format: FORMAT_BDOC

https://github.com/open-eid/digidoc4j/blob/277d6a54b01015ecc8b173822392e4c3f0013063/ddoc4j/src/main/java/org/digidoc4j/ddoc/SignedDoc.java#L55

Is it currently not supported by digidoc4j? Or It's moved to another place?

**Comment by naare** [comment]
DD4J supports creation of BDOC containers and TimeMark signatures, however default format is ASICE with LongTerm (timestamp + OCSP) signature profile . 
The usage of jdigidoc has been brought to minimal inside DD4J and it has been limited only for DDOC (to the formats you are refering to) validation.
