### ISSUE TITLE
If filename contains + sign  with spaces, then container is not validated correctly

### ISSUE THREAD

**Issue by aarepuusepp** [open-eid/digidoc4j#104]
Using Digidoc4j: 4.3.0
Container: bdoc
Filename = jagamine + müük.pdf

Validation error:
`Cannot get the pointed bytes by a reference with uri='jagamine%20+%20m%C3%BC%C3%BCk.pdf'. Reason : [Unable to find document 'jagamine   müük.pdf' (detached signature)]` - filename contains 3 space chars between jagamine and müük

**Comment by naare** [comment]
Sorry for late reply. We are aware of problems in handling + character encoding. The final solution is not yet decided but next version will introduce changes regarding this.

**Comment by naare** [comment]
I will close the issue as the 5.0.0 has been released for a year and no additional feedback has been given.
