### ISSUE TITLE
Support JakartaEE 9+

### ISSUE THREAD

**Issue by morvael** [open-eid/digidoc4j#117]
Currently the library is depending on old JakartaEE 8 APIs (javax packages) instead of newer 9+ APIs (jakarta packages). Please make a version using newer standards.

**Comment by martinounap** [comment]
Hi

Could we upgrade digidoc4j to use jakarta. Right now it is impossible move to Spring Boot 3.0.
https://spring.io/blog/2022/05/24/preparing-for-spring-boot-3-0#check-if-third-party-projects-have-jakarta-ee-9-compatible-releases

Spring Boot 2 EOL is on 18 Nov 2023. So what we do next?

**Comment by morvael** [comment]
I guess if someone really needs it there is the option to use Eclipse Transformer or even cloning the project and changing things (for example by incorporating Transformer Maven plugin to produce artifacts with Jakarta classifier). But I think the maintainers of this should add it in the first place.

**Comment by morvael** [comment]
I can confirm transformer approach works, though is pita because one needs to manually exclude wrong dependencies in correct places and add jakarta-ized versions by hand (they may need exclusions as well). Depends really on how restrictive dependency environment you have. My project is checking for duplicate dependencies and duplicate classes on classpath, so I need all this sorted out completely.

**Comment by naare** [comment]
Hello,
We are looking into how to solve it and how to proceed. Digidoc4j depends heavily on DSS library which needs to be updated as well. This update was on DSS roadmap but we have not yet seen the results regarding the update. In addition, we are supporting Java 8 so this complicates the solution even further.

**Comment by morvael** [comment]
You can keep JavaEE compatible sources and automate generating -jakarta classifier binary jar using maven plugin. It's really simple.

**Comment by naare** [comment]
We are working on merging the DSS 6.0. The release of DD4J 5.3.0 is planned in Q1 2024.

**Comment by ErkoRisthein** [comment]
Any updates on this? Spring Boot 2.7 is EOL and digidoc4j 5.2.0 is blocking our migration to Spring Boot 3.

**Comment by heititobi** [comment]
[DD4J 5.3.0](https://github.com/open-eid/digidoc4j/releases/tag/public-5.3.0) with Jakarta namespace is released and can be used in Spring Boot 3 applications.

For older DD4J versions there is an example in wiki - https://github.com/open-eid/digidoc4j/wiki/Questions-&-Answers#use-digidoc4j-in-spring-boot-3-application.
