### ISSUE TITLE
org.digidoc4j.X509Cert.loadSubjectNameParts method broken

### ISSUE THREAD

**Issue by Tujurikkuja** [open-eid/digidoc4j#13]
When trying to read all the fields from Subject of an X509 certificate, I'm getting ArrayIndexOutOfBoundsException on line 277 I guess because of the way the CN field is constructed (includes commas). All the parts up until the givenname part of the CN can be read correctly.

This line gives the error:
container.getSignatures().get(0).getSigningCertificate().getSubjectName(SubjectName.SERIALNUMBER)

Error:
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 1
	at org.digidoc4j.X509Cert.loadSubjectNameParts(X509Cert.java:277)
	at org.digidoc4j.X509Cert.getSubjectName(X509Cert.java:263)

**Comment by rvillido** [comment]
Thank you for feedback. I created a ticket and added it to our backlog. It will probably be fixed for the next release

You can track the status of the issue in Pivotal.
https://www.pivotaltracker.com/story/show/115939015

**Comment by Tujurikkuja** [comment]
For the time being I used the following regExp based on the negative lookbehind to fix the splitting of the CN field. After splitting the CN field the escape characters are still there but can be easily replaced with .replace("\\","") when creating the HashMap:

sigs.get(i).getSigningCertificate().getSubjectName().split("(?<!\\\\),")

**Comment by rvillido** [comment]
Thanks for the hint. We will look into it

**Comment by rvillido** [comment]
The bug has been fixed and will be included in the next beta release.

getSubjectName method new returns CN field without escape characters.
