### ISSUE TITLE
PKCS11SignerTestMain does not work

### ISSUE THREAD

**Issue by informatik01** [open-eid/digidoc4j#14]
Hi.

I have tried to use _prototype.PKCS11SignerTestMain_  class, which is available in the digidoc4j project, and it does not work at the moment. I have used my own real Estonian ID card (new generation, received in February 2016) and my own PIN2, but the class throws an exception when validating signature:

> Exception in thread "main" eu.europa.esig.dss.DSSException: Cryptographic signature verification has failed / Signature length not correct: got 0 but was expecting 256
> 	at eu.europa.esig.dss.xades.signature.XAdESLevelBaselineLT.checkSignatureIntegrity(XAdESLevelBaselineLT.java:104)
> 	at eu.europa.esig.dss.xades.signature.XAdESLevelBaselineLT.extendSignatureTag(XAdESLevelBaselineLT.java:75)
> 	at eu.europa.esig.dss.xades.signature.XAdESLevelBaselineT.extendSignatures(XAdESLevelBaselineT.java:140)
> 	at eu.europa.esig.dss.xades.signature.XAdESLevelBaselineT.extendSignatures(XAdESLevelBaselineT.java:73)
> 	at eu.europa.esig.dss.xades.signature.XAdESService.signDocument(XAdESService.java:95)
> 	at eu.europa.esig.dss.xades.signature.XAdESService.signDocument(XAdESService.java:45)
> 	at org.digidoc4j.impl.bdoc.xades.XadesSigningDssFacade.signDocument(XadesSigningDssFacade.java:77)
> 	at org.digidoc4j.impl.bdoc.BDocSignatureBuilder.finalizeSignature(BDocSignatureBuilder.java:82)
> 	at org.digidoc4j.impl.bdoc.BDocSignatureBuilder.invokeSigningProcess(BDocSignatureBuilder.java:66)
> 	at org.digidoc4j.SignatureBuilder.invokeSigning(SignatureBuilder.java:106)
> 	at prototype.PKCS11SignerTestMain.signWithIDCard(PKCS11SignerTestMain.java:32)
> 	at prototype.PKCS11SignerTestMain.main(PKCS11SignerTestMain.java:39)

Is this a known issue? Would appreciate any feedback as to how to make it work.

Full log can be found in the attached archive.
[PKCS11SignerTestMain.zip](https://github.com/open-eid/digidoc4j/files/179727/PKCS11SignerTestMain.zip)

**Comment by rvillido** [comment]
Thanks for the feedback. I have created a ticket in Pivotal and added it to our backlog
https://www.pivotaltracker.com/story/show/116207301

We will look into this in the near future.

Cheers!

**Comment by rvillido** [comment]
Great news, PKCS#11 support has been added with the latest beta release
https://github.com/open-eid/digidoc4j/releases/tag/public-1.0.4-beta.3

Here is an example how to use it
https://github.com/open-eid/digidoc4j/wiki/Examples-of-using-it#signing-with-a-smart-card-or-other-hardware-module-using-pkcs11

And the source works as well
https://github.com/open-eid/digidoc4j/blob/master/src/prototype/PKCS11SignerTestMain.java

Let us know if you have any problems with using it.
