### ISSUE TITLE
Serialization of an existing BDOC container or DataToSign from an exiting BDOC container is not supported

### ISSUE THREAD

**Issue by informatik01** [open-eid/digidoc4j#15]
Hi.

While using the latest (1.0.2 as of now) release of DigiDoc4j library I have encountered the following issue. If I create a new BDOC container both this container and _DataToSign_ object can be successfully serialized. But when I **read an existing BDOC container** then neither this container object nor _DataToSign_ object can be serialized.

The following exception is thrown in both cases (I used _SerializationUtils_ from Apache Commons Lang for serialization but it is irrelevant in this case):

> org.apache.commons.lang.SerializationException: java.io.NotSerializableException: java.util.zip.ZipEntry

----
Simple example to reproduce this issue:

    Container container = ContainerBuilder. 
        aContainer(). 
        fromExistingFile("some_existing_container.bdoc"). 
        build(); 

    // SignHelper is a custom helper class for reading a certificate from disk
    X509Certificate signingCert = SignHelper.readCertificate("some_signing_certificate.pem");

    // Get the data to be signed by the user
    DataToSign dataToSign = SignatureBuilder.
        aSignature(container).
        withSigningCertificate(signingCert).
        buildDataToSign();

    try {
        // Comment out either container or dataToSign serialization to see that both fail
        byte[] serializedContainer = SerializationUtils.serialize(container);
        byte[] serializedDataToSign = SerializationUtils.serialize(dataToSign);
    } catch (SerializationException e) {
        e.printStackTrace();
    }

**Comment by rvillido** [comment]
Hi,

Thank you for reporting this issue. I have created a Pivotal ticket for it https://www.pivotaltracker.com/story/show/116698977

**Comment by rvillido** [comment]
This issue has been fixed and will be included in the next beta release.

Another bug was found when trying to validate such container and a separate ticket was created for fixing that
https://www.pivotaltracker.com/story/show/117811871
