### ISSUE TITLE
Unable to open bdoc container signed with digidoc4j 1.0.2

### ISSUE THREAD

**Issue by FiremanPass** [open-eid/digidoc4j#16]
We're experiencing problems when using digidoc4j version 1.0.2 in our web application

## Use case:
User wants to add his / her signature to the existing bdoc container.

## Relevant code parts:
         //prepare the data to sign.
         String certHex = this.currentInputData.getGlobalData().get("param");
		byte[] certBytes = AllkiriUtil.hex2bin(certHex);
		certificate = AllkiriUtil.readCertificate(certBytes);
        dataToSign = SignatureBuilder
                .aSignature(container)
                .withSigningCertificate(certificate)
                .withSignatureDigestAlgorithm(DigestAlgorithm.SHA256)
                .buildDataToSign();
        byte[] digest = dataToSign.getDigestToSign();
		JsonObject response = new JsonObject(); 
		response.setStringProperty("digest", AllkiriUtil.bin2hex(digest));				
		((HttpOutputData)getOutputData()).getWriter().write(response.toString());

After the signature is sent back from the client we finalize it like this:

            Signature signature = dataToSign.finalize(signatureBytes);
            ByteArrayOutputStream stream = new ByteArrayOutputStream();
            container.addSignature(signature);
            container.save(stream);
            //save to file, send it back to client

## Expected behaviour:
User is able to open up signed container using latest version of digidoc client application.

## Actual behaviour:
Everything works as expected If the bdoc container is signed with an older version of the certificate  ESTEID_SK 2011

If user tries to sign the container with  ESTEID_SK 2015, digidoc client does not open the signed container with the following error message:

> 
> BDoc.cpp:452 Failed to parse signature 'META-INF/signatures0.xml'.
> SignatureBES.cpp:300 Failed to parse signature XML: :1:9905 error: ID value 'id-a1abfebaade6da7004edd61fd77cde27-RESPONDER_CERT' is not unique

container is attached to the issue report: 
[Liitumise_taotlus_75010430.bdoc.zip](https://github.com/open-eid/digidoc4j/files/206439/Liitumise_taotlus_75010430.bdoc.zip)

**Comment by jaanmurumets-sk** [comment]
https://www.pivotaltracker.com/story/show/117057181

**Comment by rvillido** [comment]
This bug has been fixed and will be included to the next release. Thanks for reporting it.
