### ISSUE TITLE
Why does the proxy configuration functionality keep getting pushed back?

### ISSUE THREAD

**Issue by Tujurikkuja** [open-eid/digidoc4j#18]
There's an actual need for using digidoc4j through proxys because of the internal security in companies. However the proxy configuration task in pivotal has been pushed back yet another 3 months. The systems need to be migrated to the new standard bdoc and this is just not possible without modifying the library to the extent where it cannot be updated anymore using this repository.

**Comment by rvillido** [comment]
Hello Tujurikkuja, thank you for your concern. We have increased the priority of the proxy functionality and it will be included in the next release.

Here is the ticket in Pivotal
https://www.pivotaltracker.com/story/show/116952041

Stay tuned!

**Comment by rvillido** [comment]
Hello Tujurikkuja, which type of proxy do you need? There are many kinds of proxies out there.
- authentication? plain?

Please provide more details.

We are going to test with squid 3.3.8.

**Comment by Tujurikkuja** [comment]
Hello rvillido,

Well for our specific use case at the moment we really need a plain proxy configuration for url and port but I saw that the ProxyPreferenceManager class in the apache httpclient library should indeed support basic authentication as well. I don't know if that functionality has to be used for proxy configuration or maybe it could be circumvented somehow with a custom proxy class.

Best Regards,
Rauno Veberson

**Comment by rvillido** [comment]
Thanks for the info, I will investigate.

Are you willing to do some beta testing? We are planning to add proxy for OCSP and TS requests first and it would be great if you could verify if this then works for you. After that we could add proxy for TSL as well.

**Comment by Tujurikkuja** [comment]
Yes, I would be glad to help.

**Comment by rvillido** [comment]
Good news Rauno,

A simple HTTP proxy configuration has been added. It can be configured by using:
configuration.setHttpProxyHost("cache.noile.ee");
configuration.setHttpProxyPort(8080);

or by using a YAML file
HTTP_PROXY_HOST: cache.noile.ee
HTTP_PROXY_PORT: 8080

This will be available with the beta release next week.

Please let us know if this works for you.

**Comment by rvillido** [comment]
We have released a beta version with the proxy support. Could you please test if proxy works in your environment.
https://github.com/open-eid/digidoc4j/releases/tag/public-1.0.4-beta.2

Thanks!
