### ISSUE TITLE
Hello world in digidoc4j and configuration files

### ISSUE THREAD

**Issue by antonioaraujob** [open-eid/digidoc4j#2]
I followed the documentation to build digidoc4j in a 64 bits Debian GNU/Linux wheezy:
```
git clone --recursive https://github.com/open-eid/digidoc4j.git
cd digidoc4j
ant
```
and I got the jar ```digidoc4j-0.2.9.LOCAL_BUILD.jar```. 

In a new Java project I am trying to do a Hello world program to create a container, add a text file and save it to disk (without a signature for now).

```
package testdigidoc4j;

import org.digidoc4j.Configuration;
import org.digidoc4j.Container;

public class TestDigidoc4j {

	public static void main(String[] args) {		
		Configuration configuration;
		configuration = new Configuration(Configuration.Mode.TEST);
		configuration.loadConfiguration("/home/aaraujo/desarrollo/2015/workspace-luna/JAXRS-Murachi/WebContent/WEB-INF/lib/digidoc4j.yaml");
		configuration.setTslLocation("http://localhost/trusted-test-mp.xml");
		Container container;		
		container = Container.create(Container.DocumentType.BDOC, configuration);
		container.addDataFile("/tmp/215d6ef7-d639-4191-87a1-ef68a91b2b27", "text/plain");
		System.out.println("salida." );
	}
}
```

when I run the program I get the following error:

```
06.04.2015 10:32:32.103 ERROR [TrustedListsCertificateSource.java:528] - Other problem: java.lang.NullPointerException
java.lang.NullPointerException: null
	at java.io.File.<init>(File.java:251) ~[na:1.7.0_21]
	at eu.europa.ec.markt.dss.validation102853.https.FileCacheDataLoader.get(FileCacheDataLoader.java:137) ~[dss-service-4.3.0-RC.jar:na]
	at eu.europa.ec.markt.dss.validation102853.tsl.TrustedListsCertificateSource.getTrustStatusList(TrustedListsCertificateSource.java:239) [dss-document-4.3.0-RC.jar:na]
	at eu.europa.ec.markt.dss.validation102853.tsl.TrustedListsCertificateSource.loadTSL(TrustedListsCertificateSource.java:513) [dss-document-4.3.0-RC.jar:na]
	at eu.europa.ec.markt.dss.validation102853.tsl.TrustedListsCertificateSource.init(TrustedListsCertificateSource.java:400) [dss-document-4.3.0-RC.jar:na]
	at org.digidoc4j.Configuration.getTSL(Configuration.java:718) [digidoc4j-0.2.9.LOCAL_BUILD.jar:0.2.9]
	at org.digidoc4j.impl.BDocContainer.<init>(BDocContainer.java:123) [digidoc4j-0.2.9.LOCAL_BUILD.jar:0.2.9]
	at org.digidoc4j.Container.create(Container.java:103) [digidoc4j-0.2.9.LOCAL_BUILD.jar:0.2.9]
	at testdigidoc4j.TestDigidoc4j.main(TestDigidoc4j.java:19) [bin/:na]
``` 
I think this is an error caused by a missing configuration, so I would recommend to improve the documentation to add a section describing where to put configuration files and how to use them.

**Comment by rvillido** [comment]
Thanks Antonio for the feedback. 
Could you attach the configuration files you were using: digidoc4j.yaml and trusted-test-mp.xml
We will investigate it in more detail.

**Comment by antonioaraujob** [comment]
Dear Rainer, 
thank you for taking time to see what is happening. I could not attach the files here (file type not supported) but I put them in a server: 
[digidoc4j.yaml](https://tibisay.cenditel.gob.ve/murachi/raw-attachment/wiki/WikiStart/digidoc4j.yaml)
[trusted-test-mp.xml](https://tibisay.cenditel.gob.ve/murachi/raw-attachment/wiki/WikiStart/trusted-test-mp.xml)

These are the original files that come with digidoc4j sources ([commit 5828226ed3ffbbdb5d94eb909c30cf9c296fefb6](https://github.com/open-eid/digidoc4j/commit/5828226ed3ffbbdb5d94eb909c30cf9c296fefb6)).

I would like to help to document digidoc4j to use it in a country outside Europe (We want to use in Venezuela), for example using different TSL lists as trust anchors and its configuration files.

Best regards

**Comment by rvillido** [comment]
Hi Antonio,

It looks like you have a problem with the TSL configuration file trusted-test-mp.xml.
The original test TSL configuration is slightly different.
https://github.com/open-eid/digidoc4j/blob/master/conf/trusted-test-mp.xml

You can create your own TSL with the procedure we sent to you over email. Could you please test if this will fix it?

Thanks!

**Comment by antonioaraujob** [comment]
Dear Rainer,
please excuse me you are right, the file was different. I am going to create my own TSL following the procedure and I will send to you my results. Thank you for your help.

Best regards

**Comment by kallekulp** [comment]
@rvillido Is there a possibility for you to send me the instructions as well on how to create the own TSL?
