### ISSUE TITLE
PKCS12 signature with B_BES profile is missing SignaturePolicyIdentifier tag in signature*.xml

### ISSUE THREAD

**Issue by Tujurikkuja** [open-eid/digidoc4j#20]
Hi!

We are signing a BDOC container with PKCS12 token and then sending it to the Swedbank Gateway web service. However, all the files come back with an error. Discussing with the IT department in Swedbank they came up with a reason - missing SignaturePolicyIdentifier tag in the signature*.xml. I rechecked to see if this was correct and indeed the signatures created with ID-card all have the SignaturePolicyIdentifier tag in them while the PKCS12 B_BES signature doesn't have it. Is it something that should be missing in the case of B_BES signatures? Can we add this information to the signature manually by editing the following SignatureBuilder code? I didn't find an API way of doing this though.

This is the code we are using for the signing process:

```
sigToken = new PKCS12SignatureToken(privateKey, password);
Signature sig = SignatureBuilder.aSignature(container)
			.withSignatureProfile(SignatureProfile.B_BES)
			.withRoles("ERP")
			.withSignatureToken(sigToken)
			.invokeSigning();
container.addSignature(sig);
container.saveAsFile(containerPath);
```

**Comment by rvillido** [comment]
Hi,

Thanks for the feedback.

The container with BES signature conforms with ASIC-E format where `SignaturePolicyIdentifier` is not required. `SignaturePolicyIdentifier` is required only in the old BDoc-TM format.

Right now it is not possible to create BES signatures in the old BDoc-TM format.

Note that BES signatures are missing OCSP (and Timestamp) and therefore are not valid as digital signatures by the law.

**Comment by Tujurikkuja** [comment]
Hi,

But what happens in this scenario:
1. I set the digidoc3 program default format as BDOC 2.1
2. Then I create a container with an ID-card signature, using digidoc-tool.exe in the Open-EID installation (as I've understood, this CLI program uses the same configuration file as digidoc3 program).
3. Then I add a Pkcs12 B_BES signature to the container. 

What I've understood, is that the container type (BDOC 2.1 / ASIC-E) cannot change after the first signature has been added to it. Does this mean that the container will indeed stay as BDOC 2.1 but the signature added to it conforms to the newer ASIC-E standard?

**Comment by rvillido** [comment]
Hi,

Technically the container formats are the same, but the signature formats are different. It is technically possible to mix different signature formats in a single container, but it's not recommended.

Both BDoc and ASIC-E container formats are the same Open Document Format (ODF) as a zipped archive, but signature formats are different XAdES formats. The old DDoc is a different story.

BDOC 2.1 means that an ODF container contains BDoc-TM (Timemark) signatures. BDoc-TM is a XAdES signature with an OCSP response containing TimeMark (TM).
ASIC-E means that an ODF container contains XAdES signatures with OCSP response and TimeStamp (TS).
BES signature is a XAdES signature without OCSP, TimeMark and TimeStamp.

Technically BDoc and ASIC-E are very similar formats.

You can technically mix all three types of signatures in a single container, but it's not recommended.

We have decided to add `SignaturePolicyIdentifier ` in the BES signature format for backwards compatibility with older libraries that do not recognize the new ASIC-E format.
https://www.pivotaltracker.com/story/show/120656717

Cheers!

**Comment by Tujurikkuja** [comment]
Hi!

Thanks that's amazing.

**Comment by rvillido** [comment]
Support for B_EPES profile has been added to the latest beta release
https://github.com/open-eid/digidoc4j/releases/tag/public-1.0.4-beta.3

Use `SignatureProfile.B_EPES` for creating such signatures.

Happy testing!

**Comment by priit** [comment]
To save some strugger in the future, according to recent Swedbank Gateway documentation ONLY LT_TM is supported. If you use B_BES or B_EPES profiles, then you will get following error:
 `<HGWError><Code>InvalidDigiDoc</Code><Message>Digidoc is not valid.</Message></HGWError>`
