### ISSUE TITLE
PROXY Settings

### ISSUE THREAD

**Issue by stanislav-degtjarjov** [open-eid/digidoc4j#21]
In general, there is one issue regarding proxy configuration.
If I want to use JVM proxy configuration, I need to add the same configuration to the library configuration digidoc4j.yaml.

Problem is in logic of initialization of the `HttpClientBuilder`, that ignores system properties.

`CommonsDataLoader`

``` java
private HttpClientBuilder configureProxy
```

In case of implementation and application administration it is confusing, because we need to keep same settings on environment layer and on library layer.

**Comment by rvillido** [comment]
Thank you for the feedback.

We have created a ticket on our backlog. It will take some time before we can implement this, because there are more urgent issues that have to be solved first.
https://www.pivotaltracker.com/story/show/129040397

**Comment by nostneji** [comment]
In release 1.0.7 the support of proxy configuration via JVM parameters is added.
