### ISSUE TITLE
Test tsl lication in sign finaling

### ISSUE THREAD

**Issue by zalizko** [open-eid/digidoc4j#34]
Unfortunately it's impossible to overwrite configuration value of "tslLocation" in case of finalize signing. It's possible to read only from yaml configuration, that not exactly suit our needs.

Do you have some another option for overwriting this property? It would be cool if you change it by default to the right one: https://open-eid.github.io/test-TL/tl-mp-test-EE.xml

**Comment by zalizko** [comment]
Sorry. I have found that with finalization is okay. When serialize/deserialize datatosign (sending for signing to customer) all container configuration stored also. It was my mistake.

By the way, new test tsl address should be updated asap. I thins there are many customers, who use your library. All test environments failed then..

**Comment by nostneji** [comment]
Hi! We will release new beta version in this week and there will be correct test-TSL location.

**Comment by nostneji** [comment]
The last beta-release (https://github.com/open-eid/digidoc4j/releases/tag/public-1.0.7-beta.2) contains the correct test-mode TSL URL.
