### ISSUE TITLE
Default TEST configuration TSL location url not working

### ISSUE THREAD

**Issue by johan-fm** [open-eid/digidoc4j#35]
Sometime last week we could no longer create signatures in TEST mode. We got the following error `org.digidoc4j.exceptions.TslCertificateSourceInitializationException: Unable to load the LOTL: content is empty
	at org.digidoc4j.impl.bdoc.tsl.LazyTslCertificateSource.refreshTsl(LazyTslCertificateSource.java:139)
	at org.digidoc4j.impl.bdoc.tsl.LazyTslCertificateSource.initTsl(LazyTslCertificateSource.java:124)
	at org.digidoc4j.impl.bdoc.tsl.LazyTslCertificateSource.refreshIfCacheExpired(LazyTslCertificateSource.java:102)
	at org.digidoc4j.impl.bdoc.tsl.ClonedTslCertificateSource.initializeClonedTsl(ClonedTslCertificateSource.java:51)`

It seems that the url (https://demo.sk.ee/TSL/tl-mp-test-EE.xml) specified in the [default configuration](https://github.com/open-eid/digidoc4j/blob/30329a8b78a5947a538d9da162d429f90b6e909a/src/org/digidoc4j/Configuration.java#L222) is no longer responding. Is this something which we now have to manually configure?

**Comment by nostneji** [comment]
The correct url is now https://open-eid.github.io/test-TL/tl-mp-test-EE.xml. Change is in process (sorry, but we have vacations right now).

And it is possible to define correct url in configuration file digidoc4j.yaml:
`TSL_LOCATION: https://open-eid.github.io/test-TL/tl-mp-test-EE.xml`

**Comment by johan-fm** [comment]
Since we were using the default configuration it seems a bit bad that by just disabling the url you have basically disabled singing in TEST mode for us and also created a need to update the configuration.

When the default configuration is updated should we switch back to using it or is it something which we should not rely upon?

**Comment by nostneji** [comment]
I will discuss this question with others and answer probably on next week.

**Comment by nostneji** [comment]
After discussing the current  issue with others we agreed that

1. A change of TSL URL for testing environment is rather rare event - right now we are NOT planning to change it again.
2. We are working toward situation that the default configuration should always be correct and reliable.
3. We are still retaining functionality to define TSL URL in configuration file and so we want to leave the final decision about the source of that particular information to user of library.

Right now, the last beta-release (https://github.com/open-eid/digidoc4j/releases/tag/public-1.0.7-beta.2) contains the correct test-mode TSL URL.
