### ISSUE TITLE
(DigiDoc4j, DSS) TLWellSigned parameter not working

### ISSUE THREAD

**Issue by siimsuu1** [open-eid/digidoc4j#39]
TLWellSigned is parameter between eIDAS tags in DSS constraint.xml.
Reason:  DiagnosticDataBuilder class only accepts TrustedListsCertificateSource implementation of CertificateSource interface, but DigiDoc4 has its own implementation called ClonedTslCertificateSource.

`	public DiagnosticDataBuilder trustedListsCertificateSource(CertificateSource trustedCertSource) {
		if (trustedCertSource instanceof TrustedListsCertificateSource) {
			this.trustedListCertSource = (TrustedListsCertificateSource) trustedCertSource;
		}
		return this;
	} `

**Comment by nostneji** [comment]
Created issue in JIRA: https://jira.ria.ee/browse/DD4J-170

**Comment by nostneji** [comment]
Fix for described problem is in https://github.com/open-eid/digidoc4j/releases/tag/public-2.0.0.RC.2
