### ISSUE TITLE
Different behavior between AsicFileContainerParser and AsicStreamContainerParser

### ISSUE THREAD

**Issue by siimsuu1** [open-eid/digidoc4j#41]
Only AsicStreamContainerParser class uses updateDataFilesMimeType method and therefore validating this container may get a different result compares to AsicFileContainerParser.
DSS MimeType class can throw an exception if mimeType does not match the regex
`"([\\w])*/([\\w\\-\\+\\.])*"`
Exception: 
```
eu.europa.esig.dss.DSSException: 'txt.html' is not conformant mime-type string!
	at eu.europa.esig.dss.MimeType.<init>(MimeType.java:98) ~[dss-model-5.0.d4j.5.jar:na]
	at eu.europa.esig.dss.MimeType.fromMimeTypeString(MimeType.java:215) ~[dss-model-5.0.d4j.5.jar:na]
	at org.digidoc4j.DataFile.getMimeType(DataFile.java:107) ~[digidoc4j-1.0.7.2.jar:na]
	... 100 common frames omitted
```

**Comment by nostneji** [comment]
The check that mimetype matches regex pattern "(\\w)/(\\w\\-\\+\\.)" is also in control flow of AsicFileContainerParser class, just a bit later.

**Comment by naare** [comment]
Are you sure that the later check actually works? Because using different parsers gives different results with file 23147_weak-warning-sha1.bdoc

**Comment by andresvoll** [comment]
Seems to be fixed with this [commit](https://github.com/open-eid/digidoc4j/commit/c5ede268ae8ad3985c5613601159c879e33e6a1c).
Closing issue
