### ISSUE TITLE
no main manifest attribute

### ISSUE THREAD

**Issue by nutty151** [open-eid/digidoc4j#42]
Hi,

I'm new in java and .jar application

I'm download digidoc4j-1.0.7.2.jar, then I double click it and its nothing response.

After I run it by using command java -jar "filePath". I got no main manifest attribute message

Thank you

**Comment by martinpaljak** [comment]
This is a library, not a command line tool (but I admit, it would be nice to have one based on dd4j)

**Comment by metsma** [comment]
https://github.com/open-eid/digidoc4j/releases
there is digidoc4j-1.0.8.beta.1-util.zip
