### ISSUE TITLE
container.getType() returning wrong container type

### ISSUE THREAD

**Issue by olamiko** [open-eid/digidoc4j#44]
I created an ASICS container but when I try to load the container in another project, it returns continer type as BDOC. My creation and check code is below: 
` Container container = ContainerBuilder.
                aContainer(Container.DocumentType.ASICS).
                withConfiguration(config).
                withDataFile("sample_transaction/contract.txt", "text/plain").
                build();`
and
` Container container1 = ContainerBuilder.aContainer().fromExistingFile("ContractASIC").build();`
return BDOC.

I know BDOC is similar to ASICE and ASICS, but I want it to give me the original type and not a similar type

**Comment by metsma** [comment]
bdoc is similar to ASiC-E, not ASiC-S

**Comment by olamiko** [comment]
Well, I am possibly wrong but the function returns 'BDOC' for ASICS containers I created @metsma

**Comment by olamiko** [comment]
Solved. Used the appropriate extension and it worked
