### ISSUE TITLE
HSM-st labeli järgi slotidest cerdi pärimine

### ISSUE THREAD

**Issue by webwareklem** [open-eid/digidoc4j#45]
Paluks liita , vajalik patch kui on HSM kus palju erinevaid certe

[digidocutil_label.patch.txt](https://github.com/open-eid/digidoc4j/files/2072138/digidocutil_label.patch.txt)

**Comment by metsma** [comment]
Paluks sellest teha Github pull request

**Comment by naare** [comment]
The feature is available in develop branch. Will be released with digidoc4j version 2.2.0.
