### ISSUE TITLE
Remove static reference to logger implementation

### ISSUE THREAD

**Issue by Liuskur** [open-eid/digidoc4j#46]
snippet from DDocOpener:
ch.qos.logback.classic.Logger root = (ch.qos.logback.classic.Logger)LoggerFactory.getLogger(Logger.ROOT_LOGGER_NAME);

This creates mandatory dependency to use logback classic as implementation for the slf4j api. Not all applications using digidoc4j are using logback implementation, which prevents from applications to upgrade to latest versions of digidoc4j. All such occurrences must be removed. The usage should be replaced with Logger logger = LoggerFactory.getLogger(DDocOpener.class); that you have in the beginning of the class.

**Comment by andresvoll** [comment]
Fixed with this [commit](https://github.com/open-eid/digidoc4j/commit/66e9f435fe0c6f15be69c06f57dcc036f0f6b7b2). Fix will be released with DigiDoc4j version 2.2.0.
