### ISSUE TITLE
Where is the timestamp source?

### ISSUE THREAD

**Issue by colourful-land** [open-eid/digidoc4j#47]
The wikipedia article said this about digidoc

> Additionally, during the signing, the certificate validity of each signing party is checked, and a signed timestamp is retrieved, using an OCSP service. The signed timestamp makes it possible to prove at what time a document was signed (as the timestamp is derived from the document hash) which may be important if a card is lost and used to maliciously sign documents.

It didn't give a source of this information. The signer presumably is a trust-worthy authority which will refuse to sign a timastamp that is not current. I wish to amend the wikipedia article since the authority's reliability affects that of estonian e-resident's signatures.

Thought you might know. Thanks!

**Comment by naare** [comment]
I presume you refer [this article](https://en.wikipedia.org/wiki/DigiDoc)?
In general this article needs a update and I have informed RIA about it.
