### ISSUE TITLE
What's the main class?

### ISSUE THREAD

**Issue by monperrus** [open-eid/digidoc4j#48]
I'm running digidoc4j from the command line, but the jar file has no configured Main class:

```
$ java -jar /tmp/digidoc4j-2.1.0.jar 
no main manifest attribute, in /tmp/digidoc4j-2.1.0.jar
```

There seems to be a main in `DigiDoc4J`. Is it the main class to use?

    $ java -cp /tmp/digidoc4j-2.1.0.jar org.digidoc4j.main.DigiDoc4J

**Comment by siimsuu1** [comment]
Hei,
Digidoc4j is java library. If you wanna execute digidoc4j from the command line then you have to use digidoc4j-util.jar

**Comment by monperrus** [comment]
Hi @siimsuu1, thanks for your response.

`org.digidoc4j.main.DigiDoc4J.main` is the main class.

I was confused because the [release page](https://github.com/open-eid/digidoc4j/releases/tag/public-2.1.0) contains a single Jar (`digidoc4j-2.1.0.jar`), `digidoc4j-util.jar` is hidden in a zip file.
