### ISSUE TITLE
How to use the extract feature of digidoc4j-util.jar?

### ISSUE THREAD

**Issue by monperrus** [open-eid/digidoc4j#50]
Hei,

I'm trying to use `java -jar /tmp/digidoc4j-util.jar -extract foo.bdoc` but it does not work. 

What's the correct usage?

Thanks!

**Comment by naare** [comment]
You can use `java -jar /tmp/digidoc4j-util.jar` to see all the available commands and parameters

To extract the datafile: `java -jar /tmp/digidoc4j-util.jar -in "fileNameOfSignedDoc" -extract "nameOfDataFile" "path\nameOfDataFile"`

The method has limitations, you need to know the data file filename prior the extraction. We are thinking  of adding the method for extracting all the datafiles to a folder. However, the utility tool development has lowest priority as it is for testing purposes only.

**Comment by monperrus** [comment]
> To extract the datafile: `java -jar /tmp/digidoc4j-util.jar -in "fileNameOfSignedDoc" -extract "nameOfDataFile" "path\nameOfDataFile"`

Thanks.

> We are thinking of adding the method for extracting all the datafiles to a folder. 

That would be great!
