### ISSUE TITLE
Upgrade Bouncy Castle to 1.61

### ISSUE THREAD

**Issue by elion** [open-eid/digidoc4j#58]
Upgrade Bouncy Castle Java Cryptography API dependencies to 1.61.

**Comment by naare** [comment]
This is planned for next DD4J release.

**Comment by elion** [comment]
Update: version 1.61 is available.

**Comment by naare** [comment]
1.60 was used in DD4J 3.1.0 release

**Comment by naare** [comment]
Digidoc4j 3.2.0 has been released.
