### ISSUE TITLE
Helper.deleteTmpFiles() is not thread-safe

### ISSUE THREAD

**Issue by markoleek** [open-eid/digidoc4j#62]
Helper.deleteTmpFiles() deletes all "digidoc4j*.tmp" files not taking into account which files were actually created by the current process. If there are other concurrent digidoc4j processes using temporary files (ie all StreamDocuments), they fail with FileNotFoundExceptions. 

Possible solutions:
1) As deleteOnExit() seems to be called on all temporary files anyway, one possibility is to remove the deleteTmpFiles() method call (or replace the delete() with deleteOnExit()) and live with the fact they are deleted after shutdowns
2) Delete only the temporary files created by the current process
3) Introducing a configurable delay before file deletion would also work

**Comment by naare** [comment]
This has been added to backlog for solution analysis.

**Comment by naare** [comment]
Digidoc4j 4.2.0 includes a improvement based on the proposed solution 3. Its possible to configure the temp file max age.
Given commit can be found here: https://github.com/open-eid/digidoc4j/commit/e5cf82b48cba716762bc876014c19bd277720179
