### ISSUE TITLE
SkDataLoader throws an exception with an incorrect message

### ISSUE THREAD

**Issue by zutnop** [open-eid/digidoc4j#66]
SkDataLoader.java

`throw new DSSException("Unable to process GET call for url '" + url + "'", e);`

should be

`throw new DSSException("Unable to process POST call for url '" + url + "'", e);`

**Comment by naare** [comment]
This is now fixed in develop branch and will be released in DD4J 3.2.0 version.

**Comment by naare** [comment]
DD4J 3.2.0 has been released.
