### ISSUE TITLE
NullPointerException: Error validating signatures on multiple threads: 

### ISSUE THREAD

**Issue by aarepuusepp** [open-eid/digidoc4j#67]
When logging level is in TRACE, then AsicEContainerValidator gets nullpointer exception in method extractValidatedSignatureErrors().

Problem is based on XadesValidationReportGenerator class in print() method - reports object is null.

https://github.com/open-eid/digidoc4j/blob/develop/digidoc4j/src/main/java/org/digidoc4j/impl/asic/xades/XadesValidationReportGenerator.java

private void print() {
    if (this.log.isTraceEnabled()) {
      this.log.trace("----------------Validation report---------------");
      this.log.trace(this.**reports**.getXmlDetailedReport());
      this.log.trace("----------------Simple report-------------------");
      this.log.trace(this.reports.getXmlSimpleReport());
    }
}

**Comment by naare** [comment]
This is now fixed in develop branch and will be released in DD4J 3.2.0 version.

**Comment by naare** [comment]
3.2.0 has been released.
