### ISSUE TITLE
Possible to disable LTV / configure ValidationLevel?

### ISSUE THREAD

**Issue by stefan2904** [open-eid/digidoc4j#68]
For testing we need to disable Long Term Validation (LTV), because:

`<Errors>The result of the LTV validation process is not acceptable to continue the process!</Errors>`

(Probably because we did not prepare our container for this.)

During debugging, we found the option `ValidationLevel` in DSS (_/eu/europa/esig/dss/validation/SignedDocumentValidator.java_), which is used by digidoc4j. 

Unfortunately this variable is set to `ValidationLevel.ARCHIVAL_DATA` per default and never changed or exposed. 

---

Is it possible to disable LTV? (During Container creation or container validation.)

**Comment by naare** [comment]
Changing the ValidationLevel do not help with your problem. DD4J requires Long Term signature level to accept the signature (OCSP for LT_TM and TimeStamp and OCSP for LT). Setting this parameter only determines which data is validated by DSS. The proper thing would be to find out what is wrong with your TimeStamp or OCSP that causes this error.

**Comment by stefan2904** [comment]
Thanks for your answer! 

> You can create a B_BES profile signature (a signature without Timestamp and OCSP)

We are currently creating our test containers using a B_BES profile signature (`withSignatureProfile(SignatureProfile.B_EPES);`), this removed the timestamping errors, but the LTV error still occurs. 

> You can not change the validationLevel, so you can not validate with DD4J. As Estonia only accepts LT level signatures we have no intention of enabling T and B levels. For validation you can use DSS demo

We were already thinking about using DSS directly, but then we loose all the checks DD4J does. I guess the only other option is to try to create better test data first.

**Comment by naare** [comment]
If you set digidoc4j in test mode, its possible to create test containers with TS and OCSP even with your own keys/certs as long as you upload the CA and signer cert to the demo OCSP service (https://demo.sk.ee/upload_cert/index.php). See https://github.com/open-eid/digidoc4j/wiki/Examples-of-using-it for examples

**Comment by naare** [comment]
I close this ticket as there will be no change in SW regarding this.
