### ISSUE TITLE
Publish digidoc4j in central maven repo

### ISSUE THREAD

**Issue by vershinin** [open-eid/digidoc4j#7]
It would be nice, if digidoc4j library can be accessible in central maven repo.

**Comment by rvillido** [comment]
It would be very nice indeed. It's in our future plans (not with a very high priority tho)
https://www.pivotaltracker.com/story/show/101127396

**Comment by rvillido** [comment]
Good news, DigiDoc4j is now available in Maven Central repo
http://mvnrepository.com/artifact/org.digidoc4j/digidoc4j

Cheers

**Comment by vershinin** [comment]
Thank you, guys!
