### ISSUE TITLE
Does digidoc4j support the validation of ASIC-E or ASIC-S containers that use the CAdES signature format?

### ISSUE THREAD

**Issue by olamiko** [open-eid/digidoc4j#71]
Hi, we tried validating container with the CAdES signatures but they cause errors. Is this supported in digidoc4j?

**Comment by naare** [comment]
No, Digidoc4j only supports XAdES based signatures.

**Comment by olamiko** [comment]
Thank you, is there any rationale for this choice not to support CAdES? @naare

**Comment by naare** [comment]
Digidoc4j was created as Estonian specific library. Estonia has standardized and used only XAdES based signatures so far. 

If you need to handle CAdES signatures you can directly use DSS library (provided by EU). https://github.com/esig/dss

**Comment by olamiko** [comment]
Thank you @naare
