### ISSUE TITLE
Temporary files created with prefix "temp-tsl-keystore" are never deleted.

### ISSUE THREAD

**Issue by merilynr** [open-eid/digidoc4j#72]
https://github.com/open-eid/digidoc4j/blob/d9241f859932d75897a7d4aced6a412df0f93dbd/digidoc4j/src/main/java/org/digidoc4j/impl/asic/tsl/TslLoader.java#L127

**Comment by naare** [comment]
Fix will be part of next release. Now temporary files are not created.

**Comment by naare** [comment]
fixed in develop branch.

**Comment by naare** [comment]
Released with 4.0.0.RC1
