### ISSUE TITLE
Working with Containers in offline environment.

### ISSUE THREAD

**Issue by kmetsalu** [open-eid/digidoc4j#76]
We tried using this library in offline environment and it crashed. I think because it tried to verify container signatures. Is there a possibility to skip/disable these verifications. We are only interested in extracting pdf's stored in the container. 

Maybe there is some other way to extract files contained in the container?

**Comment by naare** [comment]
We need more specifics on the crash issue. If you could provide a code snippet what you are doing and possibly the stacktrace as well.

If you are only interested in retrieving the data files then you can open the asice/bdoc container with any zip tool and extract the files. 
You can use digidoc4j for extracting the data files without any validation of signatures. Just use Container.getDataFiles() method.
Digidoc4j needs LOTL/TSL lists for signature validation. Its possible to validate signatures "offline" if these caches are pre-filled for digidoc4j beforehand if you want to validate the signature before extacting the data files.

**Comment by kmetsalu** [comment]
```java
  public static void main(String[] args) throws Exception {
    log.info("startup");
    var fileName = args[0];
    log.info("input file:{}", fileName);
    var file = Paths.get(fileName);
    if (Files.exists(file)) {
      log.info("input exists:true");
      var container = ContainerBuilder.aContainer().fromExistingFile(file.toString()).build();
      log.info("container built");
      createPreviewFromContainer(container, Paths.get(file.toString() + ".png").toFile());
    } else {
      log.info("input exists:false");
    }
    log.info("complete");
  }
```

Example of our code. When calling `.build()` on container in both configurations library starts to download certificates. We do not care about verification and just want to exract dataFile that we know is a single .pdf. In our environment there is no internet connection and we do not want to start managing somekind of certificate updating process.

**Comment by naare** [comment]
With 4.1.0-RC.1 version LOTL/TSL loading do not throw exception if it does not succeed. This should allow retrieving datafiles for your use case.
