### ISSUE TITLE
Enable compatibility for any EU ID cards

### ISSUE THREAD

**Issue by nekromoff** [open-eid/digidoc4j#77]
Currently only Estonian residency cards are supported, but any EU ID card could be supported.

**Comment by naare** [comment]
Could you please elaborate more what you mean by EU ID card support? What use case is problematic for you?

Digidoc4j is not tied to specific signature creation device, so its not Estonian card specific. You can use any signature creation device as long as it is present in EU LOTL. However, digidoc4j supports only XAdES based ASIC-E containers with TimeStamp and OCSP. So for validating the containers it applies Estonian specific rules.

**Comment by nekromoff** [comment]
OK, this would be clear: If I use ACS card reader with non-Estonian ID card
(e.g. Slovak one in this case), Digidoc does not detect any card. So maybe
it is checking for Estonian cards only.

**Comment by naare** [comment]
Are you sure this is reported to correct project? Digidoc4j is JAVA library. It does not contain any card detection mechanism in it self. You need to card specific driver to communicate with any card over PKCS11 interface.

Maybe you meant the Digidoc4 client for PC/MAC? https://github.com/open-eid/DigiDoc4-Client

**Comment by nekromoff** [comment]
I am not sure, possibly that one. I think I was a bit lost in the repos. Anyway, I am closing this as invalid.
