### ISSUE TITLE
OCSP response fails for mobile-id test person when using setTrustedTerritories()

### ISSUE THREAD

**Issue by Tujurikkuja** [open-eid/digidoc4j#80]
While using the latest digidoc4j version 4.0.3 and test person data:

```
Certificate Data for EE test-numbers (serial number is different for each number)
SERIALNUMBER = 60001019906
G = MARY ÄNN
SN = O’CONNEŽ-ŠUSLIK TESTNUMBER
CN = O’CONNEŽ-ŠUSLIK TESTNUMBER,MARY ÄNN,60001019906
```

OCSP request fails when finalizing container that has been signed with Mobile-ID test person certificate and profile LT while also limiting the trusted territories to "EE", "LV" and "LT".

```
digiDocConfiguration = new Configuration(Configuration.Mode.TEST);
digiDocConfiguration.setTrustedTerritories("EE","LT","LV");
```
`ERROR:(Signature ID: id-205fa08148980a672da84da5dbe0ec0d) - OCSP request failed. Please check GitHub Wiki for more information: https://github.com/open-eid/digidoc4j/wiki/Questions-&-Answers#if-ocsp-request-has-failed`
OCSP response is successful when using Configuration.Mode.PROD and limiting the trusted territories to the same countries.

**Comment by naare** [comment]
TEST configuration mode uses TEST LOTL (which contains test TSL) it can be found here: https://github.com/open-eid/test-TL/blob/master/tl-mp-test-EE.xml 

TEST LOTL contains "TEST" country code for Estonia:  <SchemeTerritory>EE_T</SchemeTerritory>

Setting trusted territories limits the usage only to exact country codes, which in this case do not match. You need to use EE_T. We have updated the documentation as well.
