### ISSUE TITLE
Question - How to extract/retrieve the signed content from a p7m (Cades Signature)

### ISSUE THREAD

**Issue by p4535992** [open-eid/digidoc4j#87]
Can you give a example on how to use the digidoc4j project for extract/retrieve the signed content from a p7m (Cades Signature) ?

**Comment by naare** [comment]
Digidoc4j currently do not support CAdES signatures, only XAdES signatures are supported: https://github.com/open-eid/digidoc4j#asic-e-associated-signature-container-extended-container-format

If there is need for the CAdES support we would like to hear about it more, so we could consider this as a roadmap item for the future.

**Comment by p4535992** [comment]
Sorry i don't know how i miss the description on the readme.
Ty for the clarification.
