### ISSUE TITLE
Unable to process GET call for url [https://trustlist.gov.lv/tsl/latvian-tsl.xml]

### ISSUE THREAD

**Issue by diidiiman** [open-eid/digidoc4j#89]
Hello!

Currently with the implementation straight out of the box it is not getting `latvian-tsl.xml`.

I presume that there might be a need for custom JKS, but which keys should I put there (as described here - https://github.com/open-eid/digidoc4j/wiki/Questions-&-Answers#how-to-add-trust-for-new-eu-tsl-signing-certificates)? 

As far as I understand it is not the signing per-se, but simply issue with getting country specific TSL.

Is there something else that must be done in order to be able to access this xml?

P.S. Help.

**Comment by naare** [comment]
Latvia (also Sweden and Iceland) has updated its TSL SSL certificate to a new provider that is not trusted in default Digidoc4j truststore. You can find more info here: https://github.com/open-eid/digidoc4j/wiki/Questions-&-Answers#tsl-ssl-truststore

**Comment by diidiiman** [comment]
Thank you very much! Somehow could not find this resource... Eh.
